### ISSUE TITLE
New tab for certificates, will render identical pages to badges tab.

### ISSUE THREAD

**Issue by smitbarmase** [DSC-VIT-BHOPAL/dsc-vit-bhopal.github.io#13]
The certificates tab should be there, identical to the badges tab. In the certificate tab, we need to show certificates instead of badges. Certificates will be downloadable.

**Comment by mizanxali** [comment]
Hey Smit, I would like to work on this issue. Let me know if I can!

**Comment by smitbarmase** [comment]
Sure @mizanxali. You can start working on this. Let me know if you get stuck somewhere.

**Comment by smitbarmase** [comment]
#29 Merged by @mizanxali
