### ISSUE TITLE
Fixing CSS of Team Tab to make more members visible in Mobile View.

### ISSUE THREAD

**Issue by smitbarmase** [DSC-VIT-BHOPAL/dsc-vit-bhopal.github.io#16]
![image](https://user-images.githubusercontent.com/37347831/107685727-562e4a80-6cca-11eb-9487-e82281651b35.png)
This grid should have 2 columns. Also the size of the profile, text can be reduced to achieve this.

**Comment by SHUBHANSHU-creator** [comment]
can u pls provide a readme file.....where will we find css file in the folder?

**Comment by smitbarmase** [comment]
@SHUBHANSHU-creator We are using styled-components (CSS-in-JS) in this project. You can edit CSS right into the TSX files we have created.

You can find CSS styles for this team grid [Here](https://github.com/DSCVITBHOPAL/dscvitbhopal.github.io/blob/master/pages/team.tsx) in team.tsx, Line 133 you are looking for.

**Comment by SHUBHANSHU-creator** [comment]
how can I check my the changes made by me?

**Comment by smitbarmase** [comment]
Refer to [README Getting Started Section](https://github.com/DSCVITBHOPAL/dscvitbhopal.github.io) it will help you set up local development server, where you can see changes as you edit.

**Comment by stuckinforloop** [comment]
Alright, I will like to work on this one.

**Comment by smitbarmase** [comment]
Sure @neel229. I'm assigning this issue to you.

**Comment by smitbarmase** [comment]
Merged.
