### ISSUE TITLE
Events tab will use Firebase instead of hard coded json data in directory.

### ISSUE THREAD

**Issue by smitbarmase** [DSC-VIT-BHOPAL/dsc-vit-bhopal.github.io#3]
You need to configure website for firebase and fetch events from firebase database.

**Comment by woinbo** [comment]
Hey @smitbarmase, may I work on this issue

**Comment by smitbarmase** [comment]
I have assigned you issue #4, lets finish that first.

**Comment by smitbarmase** [comment]
@woinbo Do you want to work on this issue? Let me know

**Comment by woinbo** [comment]
Let me just finish the app work then I will start with this, due 5 March I will finish up the app.

**Comment by smitbarmase** [comment]
Sure!
