### ISSUE TITLE
Website should contain few more google-like color scheme.

### ISSUE THREAD

**Issue by smitbarmase** [DSC-VIT-BHOPAL/dsc-vit-bhopal.github.io#4]
It can be improved by adding colored underline on title of every section or something similar. Any more suggestions would be appreciated.

**Comment by woinbo** [comment]
Hey @smitbarmase, may I work on this issue

**Comment by smitbarmase** [comment]
@woinbo Yes sure! What kind of changes you are thinking of? I suggest adding underline of those iconic 4 google colors in main title. I'm assigning this to you.

**Comment by woinbo** [comment]
@smitbarmase hello bhaiya, I'm in your team only DSC android developer. we are the only one integrating firebase into the app. So don't worry I will do my work perfectly, bs I need a little bit of time as I don't know more about next.js Is this ok with you?

**Comment by smitbarmase** [comment]
@woinbo Yes got it. Take your time. We will work on #3 issue together. @sarthakkundra will also join us on that issue. :)

**Comment by woinbo** [comment]
Ok sure bhaiya

**Comment by woinbo** [comment]
@smitbarmase, Hey adding four colored underlines to the text is quite difficult or I am thinking something wrong.
Either we can apply the gradient to the underline is that okay. Thank you!

**Comment by smitbarmase** [comment]
Okay. Instead can we do something like this.
![image](https://user-images.githubusercontent.com/37347831/104633757-a0211200-56c5-11eb-83ff-4822de724c7f.png)

**Comment by woinbo** [comment]
According to me, the design is perfect because google uses a simple and elegant design, and this all underline coloring and word coloring will the website look ugly. Did you (@smitbarmase ) consult our UI/UX designer for these changes because these will surely make the website look ugly?

**Comment by smitbarmase** [comment]
Not yet XD. I'm closing this issue for now. I will reopen it once, I consult UI/UX designer to make some improvements related to this.
